// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v6.33.2
// source: xcutr/v1/xcutr.proto

package xcutrpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Xcutr_Execute_FullMethodName = "/xcutr.v1.Xcutr/Execute"
)

// XcutrClient is the client API for Xcutr service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type XcutrClient interface {
	// Execute the code
	// REQUIRES: jwt-token
	Execute(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Log], error)
}

type xcutrClient struct {
	cc grpc.ClientConnInterface
}

func NewXcutrClient(cc grpc.ClientConnInterface) XcutrClient {
	return &xcutrClient{cc}
}

func (c *xcutrClient) Execute(ctx context.Context, in *ExecutionRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[Log], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Xcutr_ServiceDesc.Streams[0], Xcutr_Execute_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ExecutionRequest, Log]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Xcutr_ExecuteClient = grpc.ServerStreamingClient[Log]

// XcutrServer is the server API for Xcutr service.
// All implementations must embed UnimplementedXcutrServer
// for forward compatibility.
type XcutrServer interface {
	// Execute the code
	// REQUIRES: jwt-token
	Execute(*ExecutionRequest, grpc.ServerStreamingServer[Log]) error
	mustEmbedUnimplementedXcutrServer()
}

// UnimplementedXcutrServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedXcutrServer struct{}

func (UnimplementedXcutrServer) Execute(*ExecutionRequest, grpc.ServerStreamingServer[Log]) error {
	return status.Error(codes.Unimplemented, "method Execute not implemented")
}
func (UnimplementedXcutrServer) mustEmbedUnimplementedXcutrServer() {}
func (UnimplementedXcutrServer) testEmbeddedByValue()               {}

// UnsafeXcutrServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to XcutrServer will
// result in compilation errors.
type UnsafeXcutrServer interface {
	mustEmbedUnimplementedXcutrServer()
}

func RegisterXcutrServer(s grpc.ServiceRegistrar, srv XcutrServer) {
	// If the following call panics, it indicates UnimplementedXcutrServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Xcutr_ServiceDesc, srv)
}

func _Xcutr_Execute_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ExecutionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(XcutrServer).Execute(m, &grpc.GenericServerStream[ExecutionRequest, Log]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Xcutr_ExecuteServer = grpc.ServerStreamingServer[Log]

// Xcutr_ServiceDesc is the grpc.ServiceDesc for Xcutr service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Xcutr_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "xcutr.v1.Xcutr",
	HandlerType: (*XcutrServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Execute",
			Handler:       _Xcutr_Execute_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "xcutr/v1/xcutr.proto",
}
