// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: xcutr/v1/xcutr.proto

package xcutrpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Log struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Msg           string                 `protobuf:"bytes,1,opt,name=msg,proto3" json:"msg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Log) Reset() {
	*x = Log{}
	mi := &file_xcutr_v1_xcutr_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Log) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Log) ProtoMessage() {}

func (x *Log) ProtoReflect() protoreflect.Message {
	mi := &file_xcutr_v1_xcutr_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Log.ProtoReflect.Descriptor instead.
func (*Log) Descriptor() ([]byte, []int) {
	return file_xcutr_v1_xcutr_proto_rawDescGZIP(), []int{0}
}

func (x *Log) GetMsg() string {
	if x != nil {
		return x.Msg
	}
	return ""
}

type File struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mime          string                 `protobuf:"bytes,1,opt,name=mime,proto3" json:"mime,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Body          []byte                 `protobuf:"bytes,3,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *File) Reset() {
	*x = File{}
	mi := &file_xcutr_v1_xcutr_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *File) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*File) ProtoMessage() {}

func (x *File) ProtoReflect() protoreflect.Message {
	mi := &file_xcutr_v1_xcutr_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use File.ProtoReflect.Descriptor instead.
func (*File) Descriptor() ([]byte, []int) {
	return file_xcutr_v1_xcutr_proto_rawDescGZIP(), []int{1}
}

func (x *File) GetMime() string {
	if x != nil {
		return x.Mime
	}
	return ""
}

func (x *File) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *File) GetBody() []byte {
	if x != nil {
		return x.Body
	}
	return nil
}

type ExecutionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Language      string                 `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Files         []*File                `protobuf:"bytes,2,rep,name=files,proto3" json:"files,omitempty"`
	MaxTimeout    int64                  `protobuf:"varint,3,opt,name=max_timeout,json=maxTimeout,proto3" json:"max_timeout,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecutionRequest) Reset() {
	*x = ExecutionRequest{}
	mi := &file_xcutr_v1_xcutr_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecutionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecutionRequest) ProtoMessage() {}

func (x *ExecutionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_xcutr_v1_xcutr_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecutionRequest.ProtoReflect.Descriptor instead.
func (*ExecutionRequest) Descriptor() ([]byte, []int) {
	return file_xcutr_v1_xcutr_proto_rawDescGZIP(), []int{2}
}

func (x *ExecutionRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *ExecutionRequest) GetFiles() []*File {
	if x != nil {
		return x.Files
	}
	return nil
}

func (x *ExecutionRequest) GetMaxTimeout() int64 {
	if x != nil {
		return x.MaxTimeout
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_xcutr_v1_xcutr_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_xcutr_v1_xcutr_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_xcutr_v1_xcutr_proto_rawDescGZIP(), []int{3}
}

var File_xcutr_v1_xcutr_proto protoreflect.FileDescriptor

const file_xcutr_v1_xcutr_proto_rawDesc = "" +
	"\n" +
	"\x14xcutr/v1/xcutr.proto\x12\bxcutr.v1\"\x17\n" +
	"\x03Log\x12\x10\n" +
	"\x03msg\x18\x01 \x01(\tR\x03msg\"B\n" +
	"\x04File\x12\x12\n" +
	"\x04mime\x18\x01 \x01(\tR\x04mime\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04body\x18\x03 \x01(\fR\x04body\"u\n" +
	"\x10ExecutionRequest\x12\x1a\n" +
	"\blanguage\x18\x01 \x01(\tR\blanguage\x12$\n" +
	"\x05files\x18\x02 \x03(\v2\x0e.xcutr.v1.FileR\x05files\x12\x1f\n" +
	"\vmax_timeout\x18\x03 \x01(\x03R\n" +
	"maxTimeout\"\a\n" +
	"\x05Empty2?\n" +
	"\x05Xcutr\x126\n" +
	"\aExecute\x12\x1a.xcutr.v1.ExecutionRequest\x1a\r.xcutr.v1.Log0\x01B3Z1github.com/devathh/coderun/xcutr-service; xcutrpbb\x06proto3"

var (
	file_xcutr_v1_xcutr_proto_rawDescOnce sync.Once
	file_xcutr_v1_xcutr_proto_rawDescData []byte
)

func file_xcutr_v1_xcutr_proto_rawDescGZIP() []byte {
	file_xcutr_v1_xcutr_proto_rawDescOnce.Do(func() {
		file_xcutr_v1_xcutr_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_xcutr_v1_xcutr_proto_rawDesc), len(file_xcutr_v1_xcutr_proto_rawDesc)))
	})
	return file_xcutr_v1_xcutr_proto_rawDescData
}

var file_xcutr_v1_xcutr_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_xcutr_v1_xcutr_proto_goTypes = []any{
	(*Log)(nil),              // 0: xcutr.v1.Log
	(*File)(nil),             // 1: xcutr.v1.File
	(*ExecutionRequest)(nil), // 2: xcutr.v1.ExecutionRequest
	(*Empty)(nil),            // 3: xcutr.v1.Empty
}
var file_xcutr_v1_xcutr_proto_depIdxs = []int32{
	1, // 0: xcutr.v1.ExecutionRequest.files:type_name -> xcutr.v1.File
	2, // 1: xcutr.v1.Xcutr.Execute:input_type -> xcutr.v1.ExecutionRequest
	0, // 2: xcutr.v1.Xcutr.Execute:output_type -> xcutr.v1.Log
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_xcutr_v1_xcutr_proto_init() }
func file_xcutr_v1_xcutr_proto_init() {
	if File_xcutr_v1_xcutr_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_xcutr_v1_xcutr_proto_rawDesc), len(file_xcutr_v1_xcutr_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_xcutr_v1_xcutr_proto_goTypes,
		DependencyIndexes: file_xcutr_v1_xcutr_proto_depIdxs,
		MessageInfos:      file_xcutr_v1_xcutr_proto_msgTypes,
	}.Build()
	File_xcutr_v1_xcutr_proto = out.File
	file_xcutr_v1_xcutr_proto_goTypes = nil
	file_xcutr_v1_xcutr_proto_depIdxs = nil
}
